services:
  - type: web
    name: binary-bridges-ui
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000