services:
  - type: web
    name: binary-bridges-ui
    env: node
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production node server.js
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
